# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run npm install

on:
  push:
    branches: [ "staging" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Verify package.json exists
      run: |
        if [ ! -f package.json ]; then
          echo "Error: package.json not found!"
          exit 1
        fi

    - name: Install dependencies
      run: npm install
